version: '3.4'
services:
  honeypot:
    #image: quay.io/mnecas0/honeypot-base:latest
    build: .
    environment:
      SERVER: '127.0.0.1:8000'
      DEBUG: 1
      TCPDUMP_FILTER: ''
      TOKEN: ''
   # ports:
   #   - '123:123'
    network_mode: host
