#!/bin/bash

# Variables
TCPDUMP_FILE=${TCPDUMP_FILE:-"/tmp/tcpdump%Y%m%d_%H%M%S.pcap"}
TCPDUMP_FILTER=${TCPDUMP_FILTER:-'tcp'}
# Maximum size of file in MiB
TCPDUMP_MAX_SIZE=${TCPDUMP_MAX_SIZE:-100}
# Timeout in sec
TCPDUMP_TIMEOUT=${TCPDUMP_TIMEOUT:-3600}
TCPDUMP_EXTRAARGS=${TCPDUMP_EXTRAARGS:""}

HONEYPOT_TYPE=${HONEYPOT_TYPE:-"general"}
HONEYPOT_SERVER=${SERVER:-"127.0.0.1:8000"}
LOG_PATH=/var/log/honeypot

source tools.sh

start_tcpdump(){
    debug "Starting tcpdump"
    if [ -f $TCPDUMP_FILE ]; then
        debug "The file '$TCPDUMP_FILE' exits, removing."
        rm $TCPDUMP_FILE
    fi
    # --print
    # -U = buffer each packet insead of each line
    tcpdump -W 1 -C $TCPDUMP_MAX_SIZE -G $TCPDUMP_TIMEOUT --packet-buffered -w $TCPDUMP_FILE $TCPDUMP_FILTER -Z root -z $PWD/send_data.sh $TCPDUMP_EXTRAARGS
}

start(){
    # Setup log path
    if [ -d $LOG_PATH ]; then
        debug "Cleanup of logs"
        rm -f $LOG_PATH/*
    else
        mkdir -p $LOG_PATH
    fi

    # Start of tcpdump
    start_tcpdump
}

# Execute first param as function and pass the rest of the params to it
$1 ${@: 2}
